### ISSUE TITLE
how to connect to the mysql

### ISSUE THREAD

**Issue by stayliv3** [tobiasbaehr/dockerfiles#1]
i use docker run -P --rm  reinblau/lamp to run the image .and use docker ps to get the port of mysql

only the http port.
7bf862810eb6        reinblau/lamp       "/bin/bash /root/star"   8 minutes ago       Up 8 minutes        0.0.0.0:32785->80/tcp   f

**Comment by tobiasbaehr** [comment]
You need to start a mysql container.
E.g.
`docker run --detach --env MYSQL_ROOT_PASSWORD=root \
    --publish-all --sig-proxy \
    --volume /data/lib/mysql:/var/lib/mysql \
    --volume /data/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf \
    --name mysql mysql:5.5 >/dev/null`

Then you can use the container in the lamp container:

`docker run --detach --env VIRTUAL_HOST=myproject.dd \
    --hostname myproject.dd \
    --link mysql:db \
    --publish-all \
    --name myproject reinblau/lamp:5.6 >/dev/null`

The host to the mysql db in the myproject container is db.

**Comment by stayliv3** [comment]
thanks for all your help.
