### ISSUE TITLE
php-apache2: PDOException “could not find driver

### ISSUE THREAD

**Issue by medbenhenda** [tobiasbaehr/dockerfiles#3]
I  used the configuration in **php-apache2** and I linked the the built image of php-apache2 with mysql image I have this error 

> "PDOException “could not find driver”

I fix it by installing php_mysql. So You should add this line in your Dokerfile
`apt-get install php5-mysql`

**Comment by tobiasbaehr** [comment]
For this use-case use lamp_56.
